# Created with YamlCreate.ps1 v2.4.1 Dumplings Mod $debug=QUSU.CRLF.7-4-5.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: PhilBerndt.GPTranslate
PackageVersion: 1.3.1
PackageLocale: en-US
Publisher: Phil Berndt
PublisherUrl: https://berndt.no
PublisherSupportUrl: https://github.com/philberndt/gptranslate/issues
Author: Phil Berndt
PackageName: GPTranslate
PackageUrl: https://gptranslate.berndt.no
License: MIT
LicenseUrl: https://github.com/philberndt/gptranslate/blob/main/LICENSE
Copyright: Copyright © 2025 Phil Berndt. All rights reserved.
CopyrightUrl: https://github.com/philberndt/gptranslate/blob/main/LICENSE
ShortDescription: Fast and lightweight desktop translation application
Description: A fast and lightweight AI-powered desktop translation application built with Rust and Tauri that provides instant translation between multiple languages with global hotkey support, system tray integration, and a beautiful user interface. Supports OpenAI, Azure OpenAI, and Ollama for both cloud and local AI-powered translations.
Moniker: gptranslate
Tags:
  - translation
  - desktop
  - tauri
  - ai
  - clipboard
  - productivity
  - rust
  - svelte
  - hotkey
  - system-tray
  - ollama
  - local-ai
ReleaseNotes: |-
  🐛 Bug Fixes & Improvements:
  • Fixed translation history language detection for proper target language tracking
  • Enhanced history management with automatic language correction for Norwegian translations
  • Improved target language detection logic to correctly identify the actual language used in translations
  • Added utility function to retroactively fix language labeling in existing translation history

  🔧 Technical Improvements:
  • Better handling of alternative language switching in translation history
  • Enhanced language detection with Norwegian-specific indicators and patterns
  • Improved code formatting and consistency across translation modules
  • Cleaner icon handling with proper SVG rendering in model selector

  This is a minor maintenance release that improves the accuracy of translation history language tracking and fixes issues where the target language was incorrectly recorded when using alternative language switching.
ReleaseNotesUrl: https://github.com/philberndt/gptranslate/releases/tag/1.3.1
PurchaseUrl: https://gptranslate.berndt.no
ManifestType: defaultLocale
ManifestVersion: 1.10.0
