# Created with YamlCreate.ps1 v2.4.1 Dumplings Mod $debug=QUSU.CRLF.7-4-5.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: PhilBerndt.GPTranslate
PackageVersion: 1.3.1
Platform:
  - Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
  - interactive
  - silent
UpgradeBehavior: install
ReleaseDate: 2025-06-15
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/philberndt/GPTranslate/releases/download/1.3.1/GPTranslate_1.3.1_x64-setup.exe
    InstallerSha256: 760167DAAD71E7CB49F6A3A93E9B4D57E2782BAC2F24CC066A4E80E527C04E6D
ManifestType: installer
ManifestVersion: 1.10.0
